name: Build and deploy JAR app to Azure Web App - nostel-spring-back

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  id-token: write   # Necesario para OIDC / identidad administrada

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle (sin tests)
        run: ./gradlew clean build --no-daemon -x test

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: .

      - name: Log in to Azure using Managed Identity
        uses: azure/login@v2
        with:
          auth-type: 'IDENTITY'
          # No es necesario especificar client-id, tenant-id ni subscription-id
          # porque IDENTITY le indica que use la Managed Identity del App Service.

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nostel-spring-back'
          package: '*.jar'
