name: Build and deploy JAR app to Azure Web App - nostel-spring-back

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read    # Para actions/checkout
  id-token: write   # Para OIDC / Managed Identity

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        working-directory: ./               # Tu build.gradle está en la raíz
        run: ./gradlew clean build --no-daemon

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: 'build/libs/*.jar'          # Ruta al .jar generado por Gradle

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: .

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nostel-spring-back'    # El nombre EXACTO de tu App Service
          slot-name: 'Production'
          package: '*.jar'                  # Apunta al JAR descargado

          
