name: Build and deploy JAR app to Azure Web App - nostel-spring-back

on:
  push:
    branches:
      - master
  workflow_dispatch:

# Necesitamos permiso para OIDC y para leer el repositorio
permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Instalar Java 21
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3) Compilar con Gradle DENTRO de “Nostel2/” (donde está tu build.gradle)
      - name: Build with Gradle
        working-directory: ./Nostel2           # ← Aquí está tu subcarpeta “Nostel2”
        run: ./gradlew clean build --no-daemon

      # 4) Subir el JAR resultante (que Gradle puso en build/libs/)
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: 'Nostel2/build/libs/*.jar'     # ← Ajustado al subdirectorio

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # 5) Descargar el artefacto (.jar)
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: .

      # 6) Desplegar a Azure Web App usando OIDC / Managed Identity
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nostel-spring-back'      # ← Tu App Service EXACTO
          package: 'Nostel2/build/libs/*.jar' # ← Ruta global al JAR dentro del workspace
